### ISSUE TITLE
allowCross为false的时候，正中间的点依旧可以从上下或者左右跨过

### ISSUE THREAD

**Issue by StevenKing9** [Spikef/react-native-gesture-password#11]
问题出在这段代码：

> index文件;
>  getCrossChar(char) {
>     let middles = '13457', last = String(this.lastIndex);
>    // if ( middles.indexOf(char) > -1 || middles.indexOf(last) > -1 ) return false;
>     let point = helper.getMiddlePoint(this.state.circles[last], this.state.circles[char]);
>     for (let i=0; i < middles.length; i++) {
>         let index = middles[i];
>         if ( helper.isEquals(point, this.state.circles[index]) ) {
>             return String(index);
>         }
>     }
>     return false;
> }
> 这个方法的 // if ( middles.indexOf(char) > -1 || middles.indexOf(last) > -1 ) return false;这一句话放错的地方，应该放在最后或者直接注释。

**Comment by StevenKing9** [comment]
但是这样修改之后发现，在iphone6s plus上依然无效

**Comment by Spikef** [comment]
并没有哪里有数值对比.
