### ISSUE TITLE
请问这个组件还有在维护吗

### ISSUE THREAD

**Issue by JusticeLai** [Spikef/react-native-gesture-password#14]
![image](https://cloud.githubusercontent.com/assets/13083749/22192085/e13a69e0-e16b-11e6-9b45-903131da305a.png)

**Comment by duxiwei** [comment]
大神你好，我遇到一个问题，就是在解锁手势之后跳转页面（push方式），就会出现内存不够点击页面卡顿，而且如果用（replace方式）跳转页面的时候就会出现警告：can only update a mounted or mounting compoent.This usually means you called setState ,replaceState ,or forceUpdate on an unmounted component . This is a no-op!!!在线等

**Comment by xwartz** [comment]
@Spikef   这个项目目前是什么状态呢

**Comment by Spikef** [comment]
精力所限, 不会继续维护了
