### ISSUE TITLE
Wrong on recognize tap

### ISSUE THREAD

**Issue by pewh** [Spikef/react-native-gesture-password#15]
![peek 2017-06-14 18-56](https://user-images.githubusercontent.com/881358/27131076-562c3576-5133-11e7-93f5-522663662b1b.gif)

Tested on simulator & real device. RN 0.44.

**Comment by Benjamin369** [comment]
Have you solved it,I have the same problem,If you solved it, could you tell me how to solve it?

**Comment by Benjamin369** [comment]
add style  margintop

**Comment by Benjamin369** [comment]
add style margintop: -xxx
