### ISSUE TITLE
How to use the PasswordGesture as a subview in my Component

### ISSUE THREAD

**Issue by will86** [Spikef/react-native-gesture-password#16]
In my page Component, I have some other views, I have left an empty area for the PasswordGesture to display.
But when I layout the PasswordGesture in the area , the  full screen was occupied by the PasswordGesture.

What's the better way to use PasswordGesture as a subview?

Thanks.

**Comment by Spikef** [comment]
You can set the `style` property to overwrite the origin absolute position

**Comment by will86** [comment]
In my case, when I set `width` and `height` in the `style` , but it did not work.

I find the JavaScript file source that was written as the following.

> const Width = Dimensions.get('window').width
const Height = Dimensions.get('window').height
const Top = (Height - Width)/2.0 * 1.5
const Radius = Width / 10

so I thing the size is fixed by the above code. Would you like to  open  a param to set the size.

Thanks.
