### ISSUE TITLE
【iOS】缩略小图及圈变成点

### ISSUE THREAD

**Issue by huangxiaohao** [Spikef/react-native-gesture-password#18]
作者您好，我使用您的这个组件集成在我的项目里面，但是目前遇到了两个问题：
1、请问这个组件有缩略图thumbnails功能吗？
2、目前组件是3个点即可设置成功，请问如何设置为最少4个点才能设置成功？
非常感谢～！！！

**Comment by Spikef** [comment]
1. 没有，不是很明白手势密码和缩略图之间的关系；
2. 可以，设置outerCircle = false；
3. 请查看示例
