### ISSUE TITLE
使用react-navigation导致触摸偏移。

### ISSUE THREAD

**Issue by zhuanglong** [Spikef/react-native-gesture-password#20]

**Comment by Spikef** [comment]
请提供详细描述

**Comment by webbin** [comment]
使用react navigation以后，默认顶部会有个navigation bar，导致触摸高度算错，比实际位置要高。有个快捷的解决方法，就是直接把默认的navigation bar去掉。
`
static navigationOptions = {
    header: null,
  };
`
