### ISSUE TITLE
Please update /source/index.js

### ISSUE THREAD

**Issue by williams-voon** [Spikef/react-native-gesture-password#25]
File: /source/index.js

This line no longer valid in the latest version of RN.
let Dimensions=require("Dimensions");

Recommended:
import { Dimensions } from 'react-native'

Thank you!

**Comment by Spikef** [comment]
[react-native-gesture-password@0.3.2](https://github.com/Spikef/react-native-gesture-password/commit/8703136be192cfba808373a942afe21d48ced6e5)
