### ISSUE TITLE
计算crossChar 时的bug

### ISSUE THREAD

**Issue by Capn-lyz** [Spikef/react-native-gesture-password#27]
<img width="664" alt="96c366d4-56d7-42aa-b0e7-bed7d2537227" src="https://user-images.githubusercontent.com/18135788/39292425-b6525330-4968-11e8-9602-625f3e3dabb3.png">
计算crossChar时，中间的五个点被认为是不可能有crossChar的，但1和7，3和5是可能的，所以即使allowCross为false仍可以跳过中间的点
<img width="232" alt="image" src="https://user-images.githubusercontent.com/18135788/39292881-057e9dbe-496a-11e8-959e-97bd1b873fb4.png">
不知道是不是有意这样的，但与allowCross的直观理解不太相符。。

**Comment by Spikef** [comment]
这个是因为第一版原生实现的那版就是这样的，为了兼容所以保留了
