### ISSUE TITLE
在控件上方还有组件的话响应会不准确

### ISSUE THREAD

**Issue by LzxHahaha** [Spikef/react-native-gesture-password#4]
例如
```
<View style={{flex: 1}}>
    <View style={{height: 50}}>
        <Text>1234</Text>
    </View>
    <PasswordGesture ... />
</View>
```
之后响应会有点失灵。

在下方无影响

**Comment by LzxHahaha** [comment]
哦原来放在children里就好了。。建议在文档中说明一下

**Comment by Spikef** [comment]
@LzxHahaha 这样写就可以了，在属性列表中有提到children属性

`
<PasswordGesture ... >
    <View style={{height: 50}}>
        <Text>1234</Text>
    </View>
<PasswordGesture>
`

**Comment by chookg** [comment]
里面的组件加上onPress就会出错
`<PasswordGesture ... >
    <View onPress={alert(123} style={{height: 50}}>
        <Text>1234</Text>
    </View>
<PasswordGesture>`
