### ISSUE TITLE
allowCross为false的时候，正中间的点依旧可以从上下或者左右跨过

### ISSUE THREAD

**Issue by LzxHahaha** [Spikef/react-native-gesture-password#7]

**Comment by Spikef** [comment]
@LzxHahaha 你确定？

**Comment by StevenKing9** [comment]
我也遇到了这个问题，只有中间的点会，左右和上下回跨过，其他的不会

**Comment by StevenKing9** [comment]
问题出在： getCrossChar(char) {
        let middles = '13457', last = String(this.lastIndex);

       // if ( middles.indexOf(char) > -1 || middles.indexOf(last) > -1 ) return false;

        let point = helper.getMiddlePoint(this.state.circles[last], this.state.circles[char]);

        for (let i=0; i < middles.length; i++) {
            let index = middles[i];
            if ( helper.isEquals(point, this.state.circles[index]) ) {
                return String(index);
            }
        }

        return false;
    }
这个方法的    // if ( middles.indexOf(char) > -1 || middles.indexOf(last) > -1 ) return false;这一句话放错的地方，应该放在最后或者直接注释。
